version: '3.7'
services:
  config-server:
    container_name: config-server
    image: config-server:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - comunitas
  eureka-server:
    container_name: eureka-server
    image: eureka-server:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - comunitas
  microservicios-mysql8:
    container_name: microservicios-mysql8
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    networks:
      - comunitas
    environment: 
      MYSQL_DATABASE: db_comunitas_cloud
      MYSQL_ROOT_PASSWORD: sasa
  microservicios-postgres12:
    container_name: microservicios-postgres12
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    networks:
      - comunitas
    environment: 
      POSTGRES_DB: db_comunitas_cloud
      POSTGRES_PASSWORD: sasa
  servicios:
    container_name: servicios
    image: servicios:v1
    restart: always
    networks:
      - comunitas
    depends_on: 
      - config-server
      - eureka-server
      - microservicios-postgres12
  servicio-oauth:
    container_name: servicio-oauth
    image: servicio-oauth:v1
    ports:
      - "9100:9100"
    restart: always
    networks:
      - comunitas
    depends_on: 
      - config-server
      - eureka-server
      - servicios
  zuul-server:
    container_name: zuul-server
    image: zuul-server:v1
    ports:
      - "8090:8090"
    restart: always
    networks:
      - comunitas
    depends_on: 
      - config-server
      - eureka-server
      - servicios
      - servicio-oauth
  microservicios-rabbitmq38:
    container_name: microservicios-rabbitmq38
    image: rabbitmq:3.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - comunitas
  zipkin-server:
    container_name: zipkin-server
    image: zipkin-server:v1
    ports:
      - "9411:9411"
    restart: always
    networks:
      - comunitas
    depends_on: 
      - microservicios-rabbitmq38
      - microservicios-mysql8
    environment: 
      RABBIT_ADDRESSES: microservicios-rabbitmq38:5672
      STORAGE_TYPE: mysql
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
      MYSQL_HOST: microservicios-mysql8
networks:
  comunitas: